# Change these first
owner: thudep # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ghost Hunter homepage
    url: https://ghosthunter.thudep.com
  - name: Ghost Hunter gitea
    url: https://ghgit.thudep.com
  - name: Ghost Hunter fileserver
    url: https://ghfile.thudep.com:4433
  - name: Ghost Hunter Leaderboard
    url: https://ghosthunter.thudep.com/leaderboard
  - name: C Language Contest homepage
    url: https://clang.thudep.com
  - name: Pastebin
    url: https://bin.thudep.com
  - name: C Language Contest fileserver
    url: https://cfile.thudep.com:6443
  - name: Hedgedoc
    url: https://doc.thudep.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.thudep.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** of Tsinghua Uni. DEPSAST's services"
  introMessage: A site based on [upptime](https://upptime.js.org), a GitHub-powered open-source uptime monitor and status page)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
